### ISSUE TITLE
Speedometer or other elements possibly font changeable

### ISSUE THREAD

**Issue by naget09** [codecat/tm-dashboard#1]
Just a cosmetic request, changeable fonts mostly for the speedometer and maybe other elements.
Possibly more cosmetic stuff like outlines in the numbers to distinguish it from background elements of the same color.

**Comment by codecat** [comment]
Unfortunately text outline is not possible with NanoVG (see [this Github issue](https://github.com/memononen/nanovg/issues/58)), so I can't easily implement that. Perhaps I can add a "shadow" though, where the text is rendered twice.

As for the fonts, this would be a cool feature! I just need to work out how best to implement something like this, as changing a text setting will set the string variable in the plugin script instantly while you're typing, and I'd like to avoid needlessly calling `Resources::GetFont` every frame.

**Comment by codecat** [comment]
I've added font settings for the Gearbox, Speed, and Wheels displays, which should be available in the next update, 1.1.

I'll close this issue now as text outline is not really doable currently, if you think it's a critical feature please make a new issue for it!

**Comment by naget09** [comment]
Not at all, thank you for such a awesome tool. I'll be sure to donate when I get paid.

**Comment by codecat** [comment]
Thank you! 🥰
