### ISSUE TITLE
Add wet tire %

### ISSUE THREAD

**Issue by zai-tm** [codecat/tm-dashboard#11]
In the new update yesterday they added water, and the water effect actually is like ice, so it stays for a bit. It would be nice to add this so people know when the water effect is gone

**Comment by codecat** [comment]
I've added this! Unfortunately water is always applied to all wheels at the same time (even if you only drive through water with 1 wheel) so it's just going to display the same value for each wheel. Either way, it works!

![image](https://user-images.githubusercontent.com/136534/121868540-6a7a6680-cd01-11eb-859c-250d7361721c.png)
