### ISSUE TITLE
visual issues in keyboard display

### ISSUE THREAD

**Issue by db0z** [codecat/tm-dashboard#14]
I think these are related to analog keyboard support in 1.6 (btw very cool how it now turns analog now in my own replays i drove with non analog kb lol, interpolation stuff i guess)

1) buttons no longer have a background (they did before, I left color options untouched)
2) a small barely visible pink line is present at all times in the left key (changing x can make it show up in the right key as well)

![image](https://user-images.githubusercontent.com/25254726/122143931-21d6c080-ce5b-11eb-9034-6ac0fcd7e881.png)

**Comment by codecat** [comment]
Interesting - can you show which settings you're using?

**Comment by db0z** [comment]
![image](https://user-images.githubusercontent.com/25254726/122213834-0fd43c80-ceb2-11eb-8d27-8ba68c8b8dff.png)

![image](https://user-images.githubusercontent.com/25254726/122213808-08149800-ceb2-11eb-88fd-98db1ea09b7f.png)

the pink line is on the right after i shifted it a bit:

![image](https://user-images.githubusercontent.com/25254726/122213930-2a0e1a80-ceb2-11eb-845d-4417e9ca9017.png)

also here's the settings.ini

[Settings.ini.txt](https://github.com/codecat/tm-dashboard/files/6662737/Settings.ini.txt)

**Comment by codecat** [comment]
Thanks for the report! 🎉
