### ISSUE TITLE
chosing what you want to to show

### ISSUE THREAD

**Issue by ryleentv** [codecat/tm-dashboard#16]
Hi, i'm interested by chosing what i want to show, sometimes the all package, but from time to time just the pads or just the accelerating bar and gears etc ... is that possible ? i am really bad at coding, could you help me ? 

Thanks for the plug in, it's really cool :)

**Comment by codecat** [comment]
Yes, this is possible! You can change it in the Openplanet settings dialog under Dashboard -> General.
