### ISSUE TITLE
How does one customise the layout? 

### ISSUE THREAD

**Issue by Issung** [codecat/tm-dashboard#17]
I know in the readme it says with the open planet settings but I don't seem to have those, is that changed in a new openplanet update? A photo guide with highlights would be great! The plugin seems great but I need to customise it :) Disabled in the meantime.

**Comment by codecat** [comment]
What do you mean? They're in the "Dashboard" tab of the Openplanet settings dialog. What do you see there instead?

**Comment by Issung** [comment]
Gave it a go last night.. I'm ashamed. It was super simple, not sure what I was missing that other night, too tired I suppose. Perhaps I will make a PR later to add some instructions to the readme to other challenge people like me. Thanks for the plugin though it's super great! As is everything you do! Keep it up! (From one OSS dev to another :) )

**Comment by codecat** [comment]
Good to hear! I'd be curious to know what caused you not to see it, so perhaps I could fix it and make it easier to find in Openplanet itself. 🤔 But it sounds like you're not really sure either 😅
