### ISSUE TITLE
Brake input not displayed in replay editor

### ISSUE THREAD

**Issue by KemTM** [codecat/tm-dashboard#18]
In-game the display works fine, but when I view a replay in the replay editor the brake input somehow isn't registered. Steering + acceleration still work fine:

https://streamable.com/uyaxdy

Replay file attached just in case
[2021-07-10-04-01-42_bug miss.Replay.zip](https://github.com/codecat/tm-dashboard/files/6794435/2021-07-10-04-01-42_bug.miss.Replay.zip)

**Comment by codecat** [comment]
Fixed in 71db39fef70aecabc0892049aa38ca718e5378b2
