### ISSUE TITLE
Maniaplanet compatibility

### ISSUE THREAD

**Issue by codecat** [codecat/tm-dashboard#2]
Currently the plugin doesn't work on Maniaplanet. Couple things that need to be done:

- [x] Update Openplanet for Maniaplanet for new API additions
- [x] Maniaplanet doesn't use [`ISceneVis`](https://next.openplanet.nl/MetaNotPersistent/ISceneVis) to hold its managers (they are API-exposed via [`CSceneMgrVehicleVis`](https://mp4.openplanet.nl/Scene/CSceneMgrVehicleVis) and members), so the code to access the manager & vehicle vis states needs to be updated
- [x] The managers aren't the same as in Trackmania, so the actual vehicle vis buffer offset needs to be reverse engineered
- [ ] [`CSceneVehicleVis`](https://mp4.openplanet.nl/Scene/CSceneVehicleVis) doesn't expose anything at all, [as opposed to Trackmania](https://next.openplanet.nl/Scene/CSceneVehicleVis), so it will have to be reverse engineered

**Comment by codecat** [comment]
At offset `+38` in [`CSceneMgrVehicleVisImpl`](https://mp4.openplanet.nl/Scene/CSceneMgrVehicleVisImpl) there's a buffer of `CSceneVehicleVis*`.

At offset `+4B0` in `CSceneVehicleVis` there's `CSceneVehicleVisState`.

**Comment by codecat** [comment]
It seems like on Maniaplanet, there is no acceleration value in `CSceneVehicleVisState`, only a steering value. Doesn't bode well for proper support..

**Comment by codecat** [comment]
On Turbo:

At offset `+C` in `CSceneMgrVehicleVisImpl` there's a buffer of `CSceneVehicleVis*`.

At offset `+8C` in `CSceneVehicleVis` there's `CSceneVehicleVisState`, which **does** contain a steering and accelerate/brake! So we can definitely use this.

**Comment by codecat** [comment]
I got it to work on Turbo:

![image](https://user-images.githubusercontent.com/136534/124509816-d9178500-ddd2-11eb-81bc-3eceb7ed8fe0.png)

Pushing a commit soon!

**Comment by pekatour** [comment]
Viewing a replay's inputs in Turbo still isn't supported
![image](https://user-images.githubusercontent.com/51508663/128845432-beedfcda-072c-41cc-b3bc-2a8c471c15e2.png)

**Comment by codecat** [comment]
I checked, and unfortunately the information necessary for this to work in Turbo is only partially there. There's obviously a way to see it, but not with the way Dashboard is doing it; `CSceneVehicleVisState` has all the input values set to 0 at all times.

**Comment by codecat** [comment]
So @Atheuz added a support layer for Maniaplanet in #21, which works pretty well! I'll close this for now. If anything else needs to be done compatibility-wise, please open a new thread!
