### ISSUE TITLE
Settings preset

### ISSUE THREAD

**Issue by GreepTheSheep** [codecat/tm-dashboard#22]
Hi, I suggest a new feature for adding presets for settings and possibility to save/load settings to a file. Would be useful when we have multiple preset for display positions etc...

**Comment by codecat** [comment]
That's a cool idea! Will have to think of how to implement this the best way.. 🤔

**Comment by codecat** [comment]
There is [this plugin](https://openplanet.nl/files/149) now, so I think this is okay to close. Thanks @skybaks!
