### ISSUE TITLE
maniaplanet 4 issues

### ISSUE THREAD

**Issue by otamendi7** [codecat/tm-dashboard#26]
Hello, on mp4 we cant see the inputs working on replays and spectator mode, maybe i dont know how to do it or this option missing? thx and sorry for my bad english

**Comment by codecat** [comment]
That's unfortunately not possible on Maniaplanet. Even if you do show the inputs, Maniaplanet doesn't sync the inputs properly. See also the implementation in #21 and the original issue in #2.
