### ISSUE TITLE
Keep on using kb overlay when not using pad 

### ISSUE THREAD

**Issue by Flirno** [codecat/tm-dashboard#4]
Explicit in this clip (Massa uses his dpad on ice) : https://clips.twitch.tv/CooperativeCautiousSoymilkVoHiYo-fUdqtFfGXIczq61K

Expected behaviour :3 : would be cool to only show kb overlay (when pad is not being used, or just very gently), and not switch to pad overlay automatically when no key are pressed

**Comment by codecat** [comment]
Is he using some external tool to bind his dpad to keyboard left/right?

**Comment by codecat** [comment]
Clip is no longer available and I don't really know what the exact problem is, so I'll close this for now.
