### ISSUE TITLE
Simple request, please increase max font size?

### ISSUE THREAD

**Issue by SelkieTTV** [codecat/tm-dashboard#52]
Sorry I am new to github. I don't know how to do anything here, but I found the line of code, line 309 in Settings.as for max font size. Could someone please jack this up to like 500 or something I am trying to make a LARGE speedometer display with no border or anything. Apologies I would do it myself but I'm new and don't know how this website works. I hope this is ok.

**Comment by SelkieTTV** [comment]
I would have just edited the file myself but I could not open it with notepad++ so I didn't know what to do. If someone would like to help me do it myself to my own file instead, that would work as well!

**Comment by codecat** [comment]
I think it should be possible to Ctrl+Click the slider in the settings dialog and type a custom amount, bypassing the limit.

Doesn't hurt increasing the maximum of course, but I'm not sure about 500 😅 maybe 100 is reasonable enough.
