### ISSUE TITLE
Hide/show different parts of the UI

### ISSUE THREAD

**Issue by Banalian** [codecat/tm-dashboard#54]
Hi,

When i'm playing, I sometime like to hide the UI (using *), but i would like to be able to choose which parts of the UI gets hidden when i press that button (for exemple, hide the inputs, but keep the gears)

Thanks for the plugin, it really helped me improve :D!

**Comment by codecat** [comment]
I've implemented this for the next update!

![image](https://user-images.githubusercontent.com/136534/194615687-a2764dc3-5b47-40bf-8bad-1d3c0b061f07.png)
