### ISSUE TITLE
Possibility of making the background color fully transparent

### ISSUE THREAD

**Issue by LeoRuedas** [codecat/tm-dashboard#55]
I discovered today that it is impossible to change the Albedo of the background, and i thought it could be a good idea to add this possibility

**Comment by codecat** [comment]
What do you mean exactly? What do you want to make transparent specifically?

**Comment by codecat** [comment]
I believe you can tweak all alpha values of all background colors in the settings. Which are you trying to change?

**Comment by LeoRuedas** [comment]
i tried to tweak the alpha value of the background color of the wheels, but i found nothing

**Comment by codecat** [comment]
I know this is an old issue, but you are looking for these settings:

![image](https://user-images.githubusercontent.com/136534/194604231-7c55a8d1-243e-4ea0-9496-db8d524e4e5d.png)
