### ISSUE TITLE
Dashboard (Maniaplanet) displaying nothing

### ISSUE THREAD

**Issue by brsantoine** [codecat/tm-dashboard#56]
Hello, since today I don't have my dashboard working, here is the log and a screen of the problem:

Even after reloading, or uninstalling/install, I still have the issue.

Thanks :)

![image](https://user-images.githubusercontent.com/50876934/173048761-d1be72ce-3518-468a-9cab-76dc06f534d9.png)

![image](https://user-images.githubusercontent.com/50876934/173048604-241596e8-5775-4f83-8ecf-e89a2571e203.png)

**Comment by codecat** [comment]
Can you try setting the update branch to "edge"? I uploaded Openplanet 1.23.7 for Maniaplanet there, which should fix this problem.
