### ISSUE TITLE
Suggestion: Add a running average to accelerometer

### ISSUE THREAD

**Issue by Masterhigure** [codecat/tm-dashboard#58]
Frame-by-frame acceleration measurements can be quite hectic. I suggest smoothing things out by having a running average, with a setting going from 0 to 1 seconds. This presumably requires storing a second's worth of speed measurements in a ring buffer or something.

**Comment by Masterhigure** [comment]
After forking and actually looking at the code I realized that I'm blind and this already exists under the "Enable smoothing" setting (`Setting_Acceleration_Smoothing`), although the buffer is currently only 4 long and not resizable. I'm closing this for now, and if I decide that I want a longer / flexible buffer, I'll just make it myself and open a pull request.

**Comment by codecat** [comment]
Ah, I didn't have the chance to look at this yet, but I'm glad you found the option. 👍
