### ISSUE TITLE
When toggling "Test Mode" in Editor, the Dashboard appears

### ISSUE THREAD

**Issue by Chris92de** [codecat/tm-dashboard#6]
Expected Behaviour: Dashboard only appears when you actually start racing.

**Comment by codecat** [comment]
Hey Chris, this doesn't happen for me anymore in the latest Trackmania update. Can you confirm?

**Comment by codecat** [comment]
Nevermind, this was a bug in Dashboard, it appears again after the latest commits.

Some notes: Entity ID of the vehicle being dropped seems to have a `0x04` prefix, could probably filter that out.
