### ISSUE TITLE
Add back manual positioning/sizing settings

### ISSUE THREAD

**Issue by thaumictom** [codecat/tm-dashboard#67]
My OCD can't handle the one pixel I am off dragging it using the widgets tab. Please revert parts of aa962a5 to allow me to position/resize the widgets in-game perfectly.

**Comment by codecat** [comment]
Sure!

![image](https://user-images.githubusercontent.com/136534/221555693-54ada57e-7074-4c67-b11e-06e6033bbeac.png)

**Comment by thaumictom** [comment]
Amazing implementation! This is far better than the PR I would've proposed. Thank you 👍
