### ISSUE TITLE
Widgets change position when opening 'move widgets' menu with custom zoom

### ISSUE THREAD

**Issue by ArEyeses79** [codecat/tm-dashboard#72]
When the zoom level is different to 1, whenever the 'move widgets' mode is activated (both when opening the setting from the tab, or by turning the overlay on while the tab is selected), the widgets all move. (When zoomed in, they move away from top left)
Lars clip: <https://clips.twitch.tv/CreativeCuriousNostrilAllenHuhu-znLBqsvp-wMJtegs>

**Comment by ezio416** [comment]
In addition to moving to the bottom-right corner, I'm also seeing the widgets are drastically increasing in size. The effect stacks if the menu is closed and opened, so the widgets quickly become larger than the screen
