### ISSUE TITLE
Widgets are detached from moveable window with custom zoom

### ISSUE THREAD

**Issue by ezio416** [codecat/tm-dashboard#73]
The real widgets are gravitating towards the upper-left corner, not allowing me to put them in the bottom-right where I want them
https://youtu.be/8pRUrtyaQ0k

**Comment by codecat** [comment]
Yep, I already fixed this yesterday in defeee4dfa9730eb5ba4396bea5cf4453e239e1f. I'll publish the update now since I haven't done that yet. 👍
