### ISSUE TITLE
Gamepad - Add more colors on classic style

### ISSUE THREAD

**Issue by GreepTheSheep** [codecat/tm-dashboard#8]
We only have 2 possibility of colors on classic style, up and down
![image](https://user-images.githubusercontent.com/42576124/121424803-0c9cf600-c972-11eb-8d90-b8c2f50c5550.png)

My suggestion would to have more and add colors for directions and possibility to change also for empty (no inputs pressed, would be cool if we set opacity to 0 for this)

**Comment by codecat** [comment]
I've added a "Calssic off alpha" setting for the classic gamepad in 8a5ff1be2433f14ae9b360a47e31c08a86ad1f00. The steering direction is already configurable using the "Fill color" setting.
